language: php
php:
  - '7.0'
  - '7.1'

before_script:
  - cp .env.testing .env
  - mysql -e 'CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';'
  - mysql -e 'CREATE DATABASE homestead;'
  - mysql -e 'GRANT ALL PRIVILEGES ON homestead.* TO ‘homestead’@'localhost’;'
  - mysql -e 'FLUSH PRIVILEGES;'
  - composer self-update
  - composer install --no-interaction

script:
- vendor/bin/phpunit
