language: php
php:
  - '7.0'
  - '7.1'

services:
  - mysql

before_script:
  - cp .env.testing .env
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -u root -e "CREATE DATABASE homestead;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'homestead'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --seed

script:
- vendor/bin/phpunit
